=== Smithsonian/edan-schemas/core/core.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties":false,
	"properties": {
		"id": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/id"
		},
		"title": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/title"
		},
		"unitCode": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/unitCode"
		},
		"linkedId": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/linkedId"
		},
		"type": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/type"
		},
		"url": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/url"
		},
		"content": {
			"type": "object",
			"properties": {},
			"id": "http://edan.si.edu/schema/core/content"
		},
		"hash": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/hash",
			"pattern": "^[a-f0-9]{40}$"
		},
		"docSignature": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/docSignature"
		},
		"timestamp": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/timestamp"
		},
		"lastTimeUpdated": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/lastTimeUpdated"
		},
		"status": {
			"type": "integer",
			"id": "http://edan.si.edu/schema/core/status"
		},
		"version": {
			"type": "string",
			"id": "http://edan.si.edu/schema/core/version"
		},
		"publicSearch": {
			"type": "boolean",
			"id": "http://edan.si.edu/schema/core/publicSearch"
		},
		"linkedContent": {
			"type": "array",
			"items": {},
			"id": "http://edan.si.edu/schema/core/linkedContent"
		}
	},
	"id": "http://edan.si.edu/schema/core",
	"required": [
		"id",
		"title",
		"unitCode",
		"type",
		"url",
		"content",
		"hash",
		"docSignature",
		"timestamp",
		"lastTimeUpdated",
		"status",
		"version",
		"publicSearch"
	]
}

=== Smithsonian/edan-schemas/edan_examples/edanmdm.json
{
  "id": "ld1-1643414364024-1643414367577-1",
  "title": "Sphaerodactylus guanajae",
  "unitCode": "NMNHHERPS",
  "linkedId": "",
  "type": "edanmdm",
  "url": "edanmdm:nmnhvz_10276011",
  "content": {
    "freetext": {
      "date": [
        {
          "label": "Collection Date",
          "content": "16 Nov 2011"
        }
      ],
      "name": [
        {
          "label": "Biogeographical Region",
          "content": "Neotropical Region"
        }
      ],
      "notes": [
        {
          "label": "Record Last Modified",
          "content": "13 Aug 2024"
        },
        {
          "label": "Specimen Count",
          "content": "1"
        }
      ],
      "place": [
        {
          "label": "Place",
          "content": "Isla de Guanaja, East End, Islas de la Bah\u00eda, Honduras, North America"
        }
      ],
      "setName": [
        {
          "label": "See more items in",
          "content": "Vertebrate Zoology"
        },
        {
          "label": "See more items in",
          "content": "Amphibians & Reptiles"
        }
      ],
      "publisher": [
        {
          "label": "Published Name",
          "content": "Sphaerodactylus guanajae"
        },
        {
          "label": "Published Name",
          "content": "Sphaerodactylus millepunctatus"
        }
      ],
      "dataSource": [
        {
          "label": "Data Source",
          "content": "NMNH - Vertebrate Zoology - Herpetology Division"
        }
      ],
      "identifier": [
        {
          "label": "Accession Number",
          "content": "2059650"
        },
        {
          "label": "Other Numbers",
          "content": "Field Number : USNM-FS 256314"
        },
        {
          "label": "USNM Number",
          "content": "580000"
        }
      ],
      "objectType": [
        {
          "label": "Type Citation",
          "content": "McCranie, J. R., Hedges, S. B. 2012. Zootaxa. 3492 : 70, Figure 4."
        },
        {
          "label": "Type Status",
          "content": "Holotype"
        }
      ],
      "taxonomicName": [
        {
          "label": "Taxonomy",
          "content": "Animalia, Chordata, Vertebrata, Reptilia, Squamata, Sauria, Sphaerodactylidae"
        }
      ],
      "physicalDescription": [
        {
          "label": "Preparation",
          "content": "Ethanol"
        },
        {
          "label": "Sex",
          "content": "Male"
        }
      ]
    },
    "indexedStructured": {
      "date": ["2010s"],
      "place": ["Islas de la Bah\u00eda", "Honduras", "North America"],
      "topic": ["Reptiles", "Animals"],
      "tax_class": ["Reptilia"],
      "tax_order": ["Squamata"],
      "tax_family": ["Sphaerodactylidae"],
      "tax_phylum": ["Chordata"],
      "geoLocation": [
        {
          "L1": {
            "type": "Continent",
            "content": "North America"
          },
          "L2": {
            "type": "Country",
            "content": "Honduras"
          },
          "L3": {
            "type": "State",
            "content": "Islas de la Bah\u00eda"
          },
          "Other": {
            "type": "Locality",
            "content": "Isla de Guanaja, East End"
          },
          "points": {
            "point": {
              "latitude": {
                "type": "decimal",
                "content": "16.486"
              },
              "longitude": {
                "type": "decimal",
                "content": "-85.832"
              }
            }
          }
        }
      ],
      "object_type": ["Holotypes", "Taxonomic type specimens"],
      "tax_kingdom": ["Animalia"],
      "scientific_name": [
        "Sphaerodactylus guanajae",
        "Sphaerodactylus millepunctatus"
      ],
      "online_media_type": ["Images"]
    },
    "descriptiveNonRepeating": {
      "guid": "http://n2t.net/ark:/65665/3044db9cf-39ce-49e7-8b65-b71fa49da649",
      "title": {
        "label": "title",
        "content": "Sphaerodactylus guanajae"
      },
      "record_ID": "nmnhvz_10276011",
      "unit_code": "NMNHHERPS",
      "title_sort": "SPHAERODACTYLUS GUANAJAE",
      "data_source": "NMNH - Vertebrate Zoology - Herpetology Division",
      "record_link": "http://n2t.net/ark:/65665/3044db9cf-39ce-49e7-8b65-b71fa49da649",
      "online_media": {
        "media": [
          {
            "id": "media:NMNH-USNM580000",
            "guid": "http://n2t.net/ark:/65665/m3aa5e245a-f953-4ce1-a0a1-8b011d0dbfef",
            "type": "Images",
            "idsId": "ark:/65665/m3aa5e245af9534ce1a0a18b011d0dbfef",
            "usage": {
              "access": "Not determined"
            },
            "content": "https://ids.si.edu/ids/deliveryService/id/ark:/65665/m3aa5e245af9534ce1a0a18b011d0dbfef",
            "thumbnail": "https://ids.si.edu/ids/deliveryService/id/ark:/65665/m3aa5e245af9534ce1a0a18b011d0dbfef/90",
            "altTextAccessibility": "",
            "extDescrAccessibility": ""
          }
        ],
        "mediaCount": 1
      },
      "metadata_usage": {
        "access": "CC0"
      }
    }
  },
  "hash": "2ac12b9f3cc16d000deafe766c55554bb715f74d",
  "docSignature": "cdd66585998f162cb5568038a85443f4",
  "timestamp": "1663784720",
  "lastTimeUpdated": "1755721725",
  "status": 0,
  "version": "",
  "publicSearch": true
}
